=== inab/OEB_level2_data_migration/oeb_level2/schemas/aggregation-data-series.json
{
	"$id": "https://github.com/inab/OEB_level2_data_migration/aggregation-data-series",
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Schema that defines an aggregation of metrics focused on box-plots in an aggregation dataset",
	"type": "object",
        "properties": {
		"series_type": {
			"type": "string",
			"const": "aggregation-data-series"
		},
		"challenge_participants": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"label": {
						"title": "Label of the participant tool",
						"type": "string",
						"minLength": 1
					},
					"metric_id": {
						"title": "Label of the metric represented by this data series",
						"type": "string",
						"minLength": 1
					},
					"values": {
						"type": "array",
						"minItems": 1,
						"oneOf": [
							{
								"items": {
									"type": "object",
									"properties": {
										"v": {
											"type": "number"
										},
										"e": {
											"type": "number"
										}
									},
									"unevaluatedProperties": false,
									"required": [
										"v"
									]
								}
							},
							{
								"items": {
									"type": "number"
								}
							}
						]
					},
					"hide": {
						"title": "Should value be initially hidden?",
						"type": "boolean",
						"default": false
					}
				},
				"join_keys": [
					{
						"members": [
							"metric_id"
						],
						"schema_id": "https://github.com/inab/OEB_level2_data_migration/aggregation-data-series",
						"refers_to": "available_metrics_index"
					}
				],
				"required": [
					"label",
					"metric_id",
					"values"
				],
				"unevaluatedProperties": false
			},
			"minItems": 1
		},
                "visualization": {
                        "title": "the visualization hints",
                        "type": "object",
                        "properties": {
				"available_metrics":  {
					"title": "Axis metrics labels",
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1
					},
					"uniqueItems": true,
					"minItems": 1
				}
			},
			"oneOf": [
				{
					"properties": {
						"representations": {
							"title": "Different representations of the data series",
							"description": "These representations are focused on how the metrics, with their related data series, are conjoined. Two representations belonging to the very same group will share the same canvas. So, different groups mean different canvases.",
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"type": {
										"title": "Type of representation for this set of metrics",
										"type": "string",
										"enum": [
											"2D-plot",
											"box-plot",
											"bar-plot",
											"line-plot",
											"radar-plot"
										]
									},
									"axes_clues": {
										"title": "Clues for used axes",
										"description": "Representation clues for used axes. This is needed to adjust some parameters, like axis labels",
										"type": "array",
										"items": {
											"type": "object",
											"properties": {
												"axis": {
													"title": "Axis to be annotated",
													"type": "string",
													"enum": [
														"x",
														"y",
														"x2",
														"y2"
													]
												},
												"title": {
													"type": "string",
													"title": "Text to be shown for the axis",
													"minLength": 1
												},
												"scale": {
													"title": "Axis scale, either linear or log2 (it affects all the axes)",
													"type": "string",
													"enum": [
														"linear",
														"log2"
													],
													"default": "linear"
												}
											},
											"unevaluatedProperties": false,
											"required": [
												"axis"
											]
										},
										"minItems": 1
									},
									"metrics_series": {
										"title": "Series of involved metrics",
										"description": "Depending on the type of representation, the number of involved metrics could be 1, 2 or many",
										"type": "array",
										"items": {
											"type": "object",
											"properties": {
												"metric_id": {
													"title": "Label of the metric",
													"type": "string",
													"minLength": 1
												},
												"optimization": {
													"title": "Chart representation optimization",
													"type": "string",
													"enum": [
														"minimize",
														"maximize"
													],
													"default": "maximize"
												},
												"axis": {
													"title": "Axis for this metrics series",
													"type": "string",
													"enum": [
														"x",
														"y",
														"x2",
														"y2"
													]
												},
												"title": {
													"type": "string",
													"title": "Title to be shown about the metric in a possible axis or legend",
													"minLength": 1
												}
											},
											"unevaluatedProperties": false,
											"required": [
												"metric_id"
											],
											"join_keys": [
												{
													"members": [
														"metric_id"
													],
													"schema_id": "https://github.com/inab/OEB_level2_data_migration/aggregation-data-series",
													"refers_to": "available_metrics_index"
												},
												{
													"members": [
														"axis"
													],
													"schema_id": "https://github.com/inab/OEB_level2_data_migration/aggregation-data-series",
													"refers_to": "axes_index"
												}
											]
										},
										"minItems": 1
									},
									"type_group_id": {
										"title": "For complex representations (i.e. 2D-plot and future line-plot), the group id which helps clustering the metrics by participant. Order does matter.",
										"type": "string",
										"minLength": 1
									}
								},
								"unevaluatedProperties": false,
								"required": [
									"type",
									"metrics_series"
								],
								"index": {
									"name": "axes_index",
									"limit_scope": true,
									"members": [
										"axes_clues.axis"
									]
								}
							},
							"uniqueItems": true,
							"minItems": 1
						}
					},
					"required": [
						"representations",
						"available_metrics"
					]
				},
				{
					"properties": {
						"type": {
							"type": "string",
							"enum": [
								"2D-plot",
								"box-plot",
								"bar-plot"
							]
						},
						"optimization": {
							"title": "Chart representation optimization (valid for bar-plot and 2D-plot)",
							"type": "string",
							"enum": [
								"left",
								"right",
								"minimize",
								"maximize",
								"top-left",
								"top-right",
								"bottom-left",
								"bottom-right"
							]
						},
						"axes_scale": {
							"title": "Axes scale, either linear or log2 (it affects all the axes)",
							"type": "string",
							"enum": [
								"linear",
								"log2"
							],
							"default": "linear"
						}
					},
					"required": [
						"type",
						"available_metrics"
					]
				}
                        ],
                        "unevaluatedProperties": false
                },
		"labels": {
			"title": "Mapping labels to dataset assessment original ids. It can be an incomplete list.",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"label": {
						"title": "Label representing the participant",
						"type": "string",
						"minLength": 1
					},
					"dataset_orig_id": {
						"title": "Participant dataset original id",
						"type": "string",
						"minLength": 1
					}
				},
				"required": [
					"label",
					"dataset_orig_id"
				],
				"unevaluatedProperties": false
			},
			"minItems": 1
		}
        },
        "required": [
		"series_type",
                "challenge_participants",
                "visualization"
        ],
	"index": {
		"name": "available_metrics_index",
		"limit_scope": true,
		"members": [
			"visualization.available_metrics"
		]
	},
        "unevaluatedProperties": false
}

=== inab/OEB_level2_data_migration/aggregation_examples/boxplot-oldstyle-sample.json
{
  "challenge_participants": [
    {
      "label": "ASFL-HULAFE-Submodule",
      "metric_id": "DS",
      "values": [
        0.773483572760095,
        0.7540018561895081,
        0.7506684896368983,
        0.8061947340364144,
        0.6556722974210268,
        0.6800505658560078,
        0.48472873336725747,
        0.7836756004176819,
        0.8885440651383189,
        0.7164738614731293,
        0.8042074526329761,
        0.8057446679621061,
        0.5361080039570415,
        0.7908183722210185,
        0.6965158240986172,
        0.6113890328171785,
        0.7895869191049913,
        0.14175175494575623,
        0.8536041589610817,
        0.8537994755899613,
        0.498619305019305,
        0.5826573426573427,
        0.4818758852226827,
        0.6316517302722116,
        0.8303689772873895,
        0.12365477618140633,
        0.6266124303723248,
        0.3069806479918357,
        0.8350978493248306,
        0.7653920111213147,
        0.6128107958221647,
        0.8963605324721434,
        0.07514430229098483,
        0.016278703994966972,
        0.6343961341283249,
        0.8060100204579653,
        0.7213164663272269,
        0.34309373487275086,
        0.619093248644801,
        0.6387945056161596,
        0.5504535546023487,
        0.9046427817323556,
        0.5512294539583389,
        0.6102897322409517,
        0.7652107028651601,
        0.7155585254482681,
        0.816117222650798,
        0.841813067325748,
        0.8466046751615219,
        0.8033332555884676
      ]
    },
    {
      "label": "ASFL-HULAFE",
      "metric_id": "DS",
      "values": [
        0.9259426739970329,
        0.8986458716390144,
        0.8056844352075493,
        0.851773404705973,
        0.7558710269317592,
        0.20690316339307244,
        0.6387673361175649,
        0.7121014324290491,
        0.9182787253141831,
        0.7293347497774842,
        0.8133492822966507,
        0.9229161000815882,
        0.5435351732940855,
        0.8338263984169967,
        0.6962513599947249,
        0.5993001714121273,
        0.908937352201494,
        0.06588639342039858,
        0.896322691433021,
        0.8266321873101429,
        0.8871165107945109,
        0.7441529318887399,
        0.4280987370481413,
        0.726338070758996,
        0.8575296902819354,
        0.4764708868470481,
        0.7263192452569375,
        0.44280085712310774,
        0.8806608520630661,
        0.8413816246347159,
        0.043553312973044746,
        0.8915620607764261,
        0.11979687469364547,
        0.4527761703164499,
        0.8254607638229147,
        0.890032665814515,
        0.7795205592972623,
        0.3153873441209376,
        0.7000086387491091,
        0.6651431960610725,
        0.559808284833961,
        0.9317090056232162,
        0.3148907422075199,
        0.8061501587261114,
        0.5766367075492157,
        0.7804631858762163,
        0.8258042886332643,
        0.8154259063709961,
        0.8209998808179295,
        0.7024868299424736
      ]
    },
    {
      "label": "MITS-ErasmusMC",
      "metric_id": "DS",
      "values": [
        0.7440079836198146,
        0.6478731605939732,
        0.731805836061007,
        0.6665310711480985,
        0.8014581336517763,
        0.8657577191529634,
        0.5825499043122354,
        0.7585692745853577,
        0.6399530950424541,
        0.3529230926884255,
        0.33681525567836756,
        0.4126292397124297,
        0.4219602092978879,
        0.46688561113500004,
        0.48746124136430397,
        0.6603457172342622,
        0.7664874409369754,
        0.6127560431026114,
        0.7128328741965105,
        0.5747368216979121,
        0.41238596834355484,
        0.5996640759664429,
        0.6425786779919417,
        0.18852565103876107,
        0.7468281641891479,
        0.568695652173913,
        0.3804440592954399,
        0.3911968914359599,
        0.7667503029682353,
        0.5886836541671303,
        0.4856517741066049,
        0.6960249691875261,
        0.372048444715518,
        0.5553005492663555,
        0.5983530322265294,
        0.660643265823947,
        0.38582113431846277,
        0.665121883399759,
        0.7677441476263209,
        0.6131105455154983,
        0.6539130434782608,
        0.6609366127730791,
        0.3806941598755257,
        0.5233324985391101,
        0.7407951138102724,
        0.49126445983592304,
        0.5543058222397185,
        0.6992010828298835,
        0.7505061299451715,
        0.008719952389577457
      ]
    }
  ],
  "series_type": "aggregation-data-series",
  "visualization": {
    "available_metrics": [
      "DS"
    ],
    "type": "box-plot",
    "axes_scale": "linear"
  },
  "labels": [
    {
      "label": "ASFL-HULAFE-Submodule",
      "dataset_orig_id": "EUCAIM:PoC-2025_Segmentation_ASFL-HULAFE-Submodule_P"
    },
    {
      "label": "ASFL-HULAFE",
      "dataset_orig_id": "EUCAIM:PoC-2025_Segmentation_ASFL-HULAFE_P"
    },
    {
      "label": "MITS-ErasmusMC",
      "dataset_orig_id": "EUCAIM:PoC-2025_Segmentation_MITS-ErasmusMC_P"
    }
  ]
}

=== inab/OEB_level2_data_migration/aggregation_examples/barplot-multiple-example.json
{
    "series_type": "aggregation-data-series",
    "challenge_participants": [
        {
            "label": "Tool_A",
            "metric_id": "TE",
            "values": [
                {
                    "v": -3,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "DCA",
            "values": [
                {
                    "v": 2,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "PE",
            "values": [
                {
                    "v": 0.8,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "EO",
            "values": [
                {
                    "v": 0.25,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "AD",
            "values": [
                {
                    "v": -0.04999999999999999,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "OA",
            "values": [
                {
                    "v": 0.2222222222222222,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "FNR",
            "values": [
                {
                    "v": 0.75,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "SP",
            "values": [
                {
                    "v": 0.5555555555555556,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "DCR",
            "values": [
                {
                    "v": -3.6666666666666665,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_A",
            "metric_id": "DI",
            "values": [
                {
                    "v": 0.5333333333333333,
                    "e": 0
                }
            ]
        },



        {
            "label": "Tool_B",
            "metric_id": "TE",
            "values": [
                {
                    "v": -3.2,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "DCA",
            "values": [
                {
                    "v": 2.5,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "PE",
            "values": [
                {
                    "v": 0.79,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "EO",
            "values": [
                {
                    "v": 0.5,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "AD",
            "values": [
                {
                    "v": -0.06,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "OA",
            "values": [
                {
                    "v": 0.2,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "FNR",
            "values": [
                {
                    "v": 0.75,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "SP",
            "values": [
                {
                    "v": 0.7,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "DCR",
            "values": [
                {
                    "v": -3.2,
                    "e": 0
                }
            ]
        },
        {
            "label": "Tool_B",
            "metric_id": "DI",
            "values": [
                {
                    "v": 0.4333,
                    "e": 0
                }
            ]
        }
    ],
    "visualization": {
        "available_metrics": [
            "TE",
            "DCA",
            "PE",
            "EO",
            "AD",
            "OA",
            "FNR",
            "SP",
            "DCR",
            "DI"
        ],
        "representations": [
            {
                "type": "bar-plot",
                "metrics_series": [
                    {
                        "metric_id": "TE",
                        "optimization": "maximize",
                        "title": "%{text}"
                    },
                    {
                        "metric_id": "DCA",
                        "optimization": "maximize",
                        "title": "Difference in Conditional Acceptance"
                    },
                    {
                        "metric_id": "PE",
                        "optimization": "maximize",
                        "title": "Predictive Equality"
                    },
                    {
                        "metric_id": "EO",
                        "optimization": "maximize",
                        "title": "Equal Opportunity"
                    },
                    {
                        "metric_id": "AD",
                        "optimization": "maximize",
                        "title": "Accuracy Difference"
                    },
                    {
                        "metric_id": "OA",
                        "optimization": "maximize",
                        "title": "Overall accuracy"
                    },
                    {
                        "metric_id": "FNR",
                        "optimization": "maximize",
                        "title": "False Negative Rate"
                    },
                    {
                        "metric_id": "SP",
                        "optimization": "maximize",
                        "title": "Statistical Parity"
                    },
                    {
                        "metric_id": "DCR",
                        "optimization": "maximize",
                        "title": "Difference in Conditional Rejection"
                    },
                    {
                        "metric_id": "DI",
                        "optimization": "maximize",
                        "title": "Disparate Impact"
                    }
                ],
                "type_group_id": "barplot-multiple-1"
            }
        ]
    },
    "labels": [
        {
            "label": "Tool_A",
            "dataset_orig_id": "OEBDTOOL1000A"
        },
        {
            "label": "Tool_B",
            "dataset_orig_id": "OEBDTOOL0000B"
        }
    ]
}
